import { StyleSheet, Platform } from "react-native";
import { heightPercentageToDP, widthPercentageToDP } from "react-native-responsive-screen";

const fontFamily =
  Platform.OS === "android" ? "sans-serif-condensed" : "Avenir Next";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  row: {
    display: "flex",
    flexDirection: "row",
  },
  rowCenter: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  center: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  rowCenterHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    margin: Platform.OS === "ios" ? 20 : 40,
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 20,
    marginTop: Platform.OS === "android" ? 50 : 30,
    marginRight: 20,
  },
  top: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
    marginRight: 10,
  },
  topHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: Platform.OS === "ios" ? 20 : 40,
    marginRight: 10,
  },
  features: {
    fontSize: 18,
    //fontWeight: "bold",
    color: "#333333",
    textAlign: "center",
    marginLeft: 20,
    marginTop: 20,
    //fontFamily,
  },
  text1: {
    fontSize: 16,
    //fontWeight: "bold",
    color: "#333333",
    //fontFamily,
  },
  bottomText: {
    fontSize: 14,
    color: "#3E5670",
    //fontFamily,
    margin: 10,
  },
  bottomText1: {
    fontSize: 14,
    color: "#3E5670",
    //fontFamily,
    //fontWeight: "bold",
    margin: 10,
  },
  section1: {
    width: Platform.OS === "ios" ? 350 : "99%",
    marginLeft: Platform.OS === "ios" ? 20 : 5,
    marginTop: 10,
    marginBottom: 10,
    height: Platform.OS === "ios" ? 115 : 110,
    borderRadius: 10,
  },
  dashboardContainerImage: {
    // width: Platform.OS === "ios" ? 350 : 325,
    width: widthPercentageToDP("90%"),
    marginLeft: 10,
    marginTop: 10,
    marginBottom: 10,
    height: Platform.OS === "ios" ? 115 : 100,
  },
  section2: {
    width: Platform.OS === "ios" ? 360 : 320,
    height: Platform.OS === "ios" ? 140 : 125,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    marginLeft: 15,
    marginTop: Platform.OS === "ios" ? 10 : 20,
    marginBottom: 10,
  },
  child: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  child1Text: {
    fontSize: 14,
    //fontFamily,
    color: "#FFFFFF",
  },
  child1Text1: {
    fontSize: 18,
    //fontWeight: "bold",
    //fontFamily,
    color: "#FFFFFF",
  },
  token: {
    width: 120,
    height: 50,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 20,
    marginLeft: 10,
  },
  tokenName: {
    fontSize: 14,
    //fontWeight: "bold",
    color: "#022141",
    textAlign: "center",
    //fontFamily,
  },
  tokenAmount: {
    fontSize: 25,
    //fontWeight: "bold",
    color: "#4D4D5B",
    textDecorationColor: "#8C8CA1",
    textDecorationLine: "underline",
    //fontFamily,
  },
  tranxFee: {
    fontSize: 15,
    color: "#3E5670",
    padding: 5,
  },
  tranxFeeAmount: {
    fontSize: 18,
    color: "#3E5670",
    padding: 5,
  },
  bottomText1: {
    fontSize: 14,
    color: "#022141",
    //fontFamily,
  },
  section3: {
    width: Platform.OS === "ios" ? 360 : 320,
    height: 60,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    marginLeft: 15,
    marginTop: 10,
    marginBottom: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  section4: {
    // width: Platform.OS === "ios" ? 360 : 320,
    width: widthPercentageToDP("90%"),
    // height: Platform.OS === "ios" ? 85 : 60,
    height: heightPercentageToDP("12%"),
    borderWidth: 1,
    borderColor: "#D9D9D9",
    borderRadius: 10,
    marginLeft: 10,
    // marginTop: Platform.OS === "ios" ? 10 : 20,
    marginTop: heightPercentageToDP(10),
    marginBottom: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(239, 237, 237, 0.5)",
  },
  walletAddress: {
    fontSize: 16,
    //fontWeight: "bold",
    color: "#8C8CA1",
    marginLeft: 10,
    //fontFamily,
  },
  paste: {
    width: 100,
    height: 50,
    backgroundColor: "#D8D8FF",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 5,
  },
  pasteText: {
    fontSize: 12,
    textAlign: "center",
    color: "#0000FF",
    //fontFamily,
  },
  newCardText: {
    fontSize: 14,
    //fontWeight: "bold",
    color: "#0000FF",
    //fontFamily,
  },
  button: {
    backgroundColor: "#000000",
    margin: 10,
    height: 48,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    position: "absolute",
    bottom: 10,
    left: 10,
    right: 10,
  },
  buttonText: {
    color: "white",
    //fontWeight: "bold",
    //fontFamily,
  },
  searchTokenText: {
    fontSize: 16,
    color: "#8C8CA1",
    //fontFamily,
  },
  search: {
    width: Platform.OS === "ios" ? 360 : "90%",
    height: 60,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    marginLeft: 20,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 30,
    marginBottom: 20,
  },
  tokenName1: {
    width: Platform.OS === "ios" ? 366 : "90%",
    backgroundColor: "rgba(216, 216, 255, 0.7)",
    boxShadow: "0px 1px 7px rgba(0, 0, 0, 0.1)",
    height: 70,
    borderRadius: 10,
    marginTop: 15,
    marginLeft: 20,
    marginRight: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  tokenName2: {
    width: Platform.OS === "ios" ? 366 : "90%",
    borderWidth: 1.2,
    borderColor: "rgba(234, 234, 234, 0.7)",
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.1)",
    height: 70,
    borderRadius: 10,
    marginTop: 15,
    marginLeft: 20,
    marginRight: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  paymentMethod: {
    width: Platform.OS === "ios" ? 366 : "90%",
    border: "1px solid #0000FF",
    background: "#FFFFFF",
    height: 80,
    borderRadius: 10,
    borderColor: "#0000FF",
    borderWidth: 1,
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  paymentMethod1: {
    width: Platform.OS === "ios" ? 366 : "90%",
    border: "1px solid #EAEAEA",
    background: "#FFFFFF",
    borderColor: "#EAEAEA",
    borderWidth: 1.2,
    height: 80,
    borderRadius: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 20,
    marginRight: 10,
  },
  tokenNameText: {
    fontSize: 13,
    //fontWeight: "bold",
    color: "#4D4D5B",
    //fontFamily,
  },
  tokenNameSubText: {
    fontSize: 16,
    //fontWeight: "bold",
    color: "#022141",
    padding: 5
    //fontFamily,
  },
  selectCardContainer: {
    width: Platform.OS === "ios" ? 350 : 320,
    borderColor: "#0000FF",
    borderWidth: 1,
    height: 50,
    borderRadius: 5,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    marginLeft: 25,
  },
  newCardButton: {
    backgroundColor: "rgba(216, 216, 255, 0.7)",
    width: 180,
    height: 60,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    position: "absolute",
    left: Platform.OS === "ios" ? 117 : 90,
    top: Platform.OS === "ios" ? 500 : 400,
  },
  fillInfo: {
    width: Platform.OS === "ios" ? 375 : "90%",
    backgroundColor: "#FCF6DE",
    height: 65,
    borderRadius: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    marginLeft: 20,
  },
  filInfoText: {
    color: "#C0AE7E",
    fontSize: 16,
    //fontWeight: "bold",
    paddingRight: 20,
    //fontFamily,
  },
  spaceBetween: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  selectAddress: {
    display: "flex",
    flexDirection: "row",
    margin: 20,
  },
  firstName: {
    width: Platform.OS === "ios" ? 180 : 150,
    borderColor: "#D1D5DB",
    borderWidth: 1,
    height: 60,
    borderRadius: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardNumber: {
    width: Platform.OS === "ios" ? 375 : "100%",
    borderColor: "#D1D5DB",
    borderWidth: 1,
    height: 60,
    borderRadius: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  billingAddress: {
    width: Platform.OS === "ios" ? 375 : "95%",
    height: Platform.OS === "ios" ? 120 : 110,
    borderRadius: 10,
    borderColor: "#0000FF",
    borderWidth: 1,
    padding: 10,
  },
  conversioncontainer: {
    width: Platform.OS === "ios" ? 360 : "90%",
    height: Platform.OS === "ios" ? 60 : 50,
    borderRadius: 10,
    borderColor: "#D1D5DB",
    borderWidth: 1,
    margin: 20,
  },
  addressText: {
    color: "#757575",
    fontSize: 14,
    paddingTop: 10,
    //fontFamily,
  },
  addresssSubText: {
    color: "#252525",
    fontSize: 16,
    paddingTop: 10,
    //fontFamily,
  },
  addresssLargeText: {
    color: "#252525",
    fontSize: 18,
    //fontWeight: "bold",
    paddingTop: 10,
    //fontFamily,
  },
  divider: {
    width: 1,
    height: 60,
    backgroundColor: "#D1D5DB",
  },
  morePaymentText: {
    color: "#686868",
    fontSize: 16,
    padding: 10
    //fontFamily,
  },
  tranxSummaryText: {
    color: "#686868",
    fontSize: 14,
    //fontFamily,
  },
  checkDashboard: {
    display: "flex",
    margin: 50,
  },
  borrowContainer: {
    width: Platform.OS === "ios" ? 360 : "90%",
    height: Platform.OS === "ios" ? 143 : 133,
    borderRadius: 10,
    borderColor: "#D1D5DB",
    borderWidth: 1,
    marginTop: 40,
    marginLeft: 20,
    marginRight: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
  },
  borrowSubContainer: {
    width: Platform.OS === "ios" ? 360 : "90%",
    height: Platform.OS === "ios" ? 191 : 181,
    borderRadius: 10,
    borderColor: "#D1D5DB",
    borderWidth: 1,
    marginTop: 40,
    marginLeft: 20,
    marginRight: 20,
    display: "flex",
    // alignItems: "center",
    justifyContent: "space-between",
  },
  borrowInnerContainer: {
    width: Platform.OS === "ios" ? 180 : 160,
    height: Platform.OS === "ios" ? 130 : 120,
    backgroundColor: "#000000",
    margin: 5,
    // marginLeft: 20,
    // marginRight: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  borrowBottomText: {
    color: "#FFFFFF",
    fontSize: 30,
    //fontWeight: "bold",
    paddingRight: 5,
    //fontFamily,
  },
  headerText: {
    fontSize: 18,
    //fontWeight: "bold",
    color: "#022141",
    // paddingTop: 5,
    //fontFamily,
  },
  gasText: {
    color: '#686868',
    fontSize: 18,
    padding: 10
  },
  gasFee: {
    width: Platform.OS === "ios" ? 360 : 320,
    height: Platform.OS === "ios" ? 60 : 50,
    borderWidth: 1,
    borderColor: "#D9D9D9",
    borderRadius: 10,
  },
  gasLimit: {
    width: Platform.OS === "ios" ? 360 : 320,
    height: Platform.OS === "ios" ? 60 : 50,
    backgroundColor: "rgba(239, 237, 237, 0.4)",
    borderWidth: 1,
    borderColor: "#D9D9D9",
    borderRadius: 10,
  },
  horizontalSeperator: {
    width: 1,
    height: Platform.OS === "ios" ? 60 : 50,
    backgroundColor: "#D9D9D9",
    borderWidth: 1,
    borderColor: "#D9D9D9",
    borderRadius: 10,
  },
  noteContainer: {
    width: "100%",
    height: 49,
    fontSize: 16,
    backgroundColor: "rgba(255, 167, 81, 0.25)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  noteText: {
    color: "#272833",
    fontSize: 16,
    textAlign: "center"
  },
  inputAddress: {
    width: "50%",
    height: "100%",
    paddingLeft: 10,
    paddingTop: Platform.OS === "android" ? 0 : 15,
    paddingBottom: Platform.OS === "android" ? 0 : 10
  }
});

export default styles;
