import { StyleSheet, Platform } from "react-native";
import { widthPercentageToDP } from "react-native-responsive-screen";

const fontFamily =
  Platform.OS === "android" ? "sans-serif-condensed" : "Avenir Next";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  imageContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 20,
    marginTop: Platform.OS === "android" ? 50 : 30,
    marginRight: 20,
  },
  headerText: {
    fontSize: 18,
    //fontWeight: "bold",
    color: "#022141",
    // paddingTop: 5,
    //fontFamily,
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 20,
    marginTop: 20,
    marginRight: 20,
  },
  top: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    // marginLeft: 10,
    marginTop: 5,
    marginRight: 10,
  },
  topHeader: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: Platform.OS === "android" ? 50 : 30,
    marginRight: 10,
  },
  headerImage2: {
    width: 20,
    height: 20,
    marginRight: 20,
  },
  headerImage3: {
    width: 30,
    height: 30,
  },
  dashboard: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    margin: 70,
  },
  comingSoon: {
    fontSize: 40,
    //fontWeight: "bold",
    color: "#333333",
    marginTop: 20,
    //fontFamily,
  },
  rocket: {
    width: 126,
    height: 126,
  },
  features: {
    fontSize: 16,
    //fontWeight: "bold",
    color: "#333333",
    textAlign: "center",
    marginLeft: 10,
    marginTop: 20,
    marginBottom: 30,
    //fontFamily,
  },
  bodyContainer: {
    // width: Platform.OS === "android" ? 320 : 360,
    width: widthPercentageToDP("85%"),
    height: 85,
    borderRadius: 10,
    backgroundColor: "#EAEAEA80",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: Platform.OS === "android" ? 20 : 30,
    // marginRight: Platform.OS === "android" ? 20 : 0,
    // marginBottom: 10,
    marginLeft: Platform.OS === "android" ? 15 : 20,
  },
  marginTop: {
    marginTop: 10,
  },
  text1: {
    fontSize: 16,
    //fontWeight: "bold",
    color: "#333333",
    //fontFamily:
    //Platform.OS === "android" ? "sans-serif-condensed" : "Avenir Next",
  },
  text2: {
    fontSize: 14,
    color: "#8C8CA1",
    paddingTop: 5,
    //fontFamily,
  },
  icon: {
    width: 50,
    height: 50,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 20,
    marginRight: 10,
    backgroundColor: "#000000",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  section1: {
    // width: Platform.OS === 'ios' ? 350 : 320,
    width: widthPercentageToDP("90%"),
    height: Platform.OS === "ios" ? 100 : 95,
    // background: "rgba(255, 255, 255, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(196, 196, 196, 0.5)",
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 20,
  },
  profile: {
    width: 60,
    height: 60,
  },
  section1Text: {
    //fontWeight: "bold",
    fontSize: 18,
    lineHeight: 27,
    color: "#333333",
    //fontFamily
  },
  section1SubText: {
    // //fontWeight: "bold",
    fontSize: 14,
    lineHeight: 21,
    color: "#686868",
    //fontFamily
  },
  profileText: {
    //fontWeight: "bold",
    fontSize: 15,
    lineHeight: 27,
    color: "#333333",
    //fontFamily
  },
  section2: {
    // width: Platform.OS === 'ios' ? 350 : 320,
    width: widthPercentageToDP("90%"),
    height: 300,
    borderWidth: 1,
    borderColor: "rgba(196, 196, 196, 0.5)",
    borderRadius: 10,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 30,
  },
  profileSection2: {
    width: Platform.OS === "ios" ? 350 : 330,
    // height: 300,
    height: 120,
    borderWidth: 1,
    borderColor: "rgba(196, 196, 196, 0.5)",
    borderRadius: 10,
    margin: 20,
  },
  section2Details: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: 10,
  },
  verticalSepperatorLine: {
    height: 1,
    backgroundColor: "rgba(50,52,54,0.2)",
    marginTop: 10,
    marginBottom: 10,
  },
  security: {
    fontSize: 14,
    lineHeight: 21,
    color: "#686868",
    marginLeft: 20,
    marginTop: 40,
    //fontFamily
  },
  nameText: {
    fontSize: 16,
    //fontWeight: "bold",
    lineHeight: 24,
    color: "#333333",
    //fontFamily
  },
  profileContainer: {
    display: "flex",
    marginTop: 50,
    //   flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  transaction: {
    color: "#333333",
    fontSize: 18,
    //fontWeight: "bold",
    // textAlign: 'center',
    marginTop: 10,
    //fontFamily,
  },
  date: {
    color: "#686868",
    fontSize: 12,
    //fontWeight: "bold",
    // fontWeight: 'bold',
    // textAlign: 'center',
    marginTop: 20,
    marginBottom: 30,
    marginLeft: 10,
    //fontFamily,
  },
  tranxContainer: {
    borderRadius: 5,
    borderWidth: 0.3,
    borderColor: "#022141",
    width: Platform.OS === "android" ? 330 : 370,
    marginTop: 20,
  },
  cardDetails: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: 10,
  },
  price: {
    color: "#E63946",
    fontSize: 14,
    //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  verticalSepperatorLine: {
    height: 1,
    backgroundColor: "rgba(50,52,54,0.2)",
    marginTop: 10,
    marginBottom: 10,
  },
  subContainer: {
    marginLeft: 20,
    marginRight: 20,
    marginTop: 40,
  },
  boxContainer: {
    width: 50,
    height: 50,
    backgroundColor: "#000000",
  },
});

export default styles;
