import { StyleSheet, Platform } from "react-native";

const fontFamily =
  Platform.OS === "android" ? "sans-serif-condensed" : "Avenir Next";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  imageContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 20,
    marginTop: Platform.OS === "android" ? 50 : 30,
    marginRight: 20,
    marginBottom: 20,
  },
  headerText: {
    fontSize: 18,
    //fontWeight: "bold",
    color: "#022141",
    paddingTop: 5,
    //fontFamily,
  },
  previewHeader: {
    display: "flex",
    flexDirection: "row",
    // justifyContent: 'space-between',
    marginLeft: 20,
    marginTop: Platform.OS === "android" ? 50 : 30,
    marginRight: 20,
  },
  headerImage2: {
    width: 20,
    height: 20,
    marginRight: 20,
  },
  headerImage3: {
    width: 30,
    height: 30,
  },
  marginx2: {
    margin: 20,
  },
  pills: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    // marginTop: 10,
    marginBottom: 10,
    marginRight: 30,
    marginLeft: Platform.OS === "android" ? 5 : 30,
  },
  pillsContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: 40,
    borderRadius: 5,
    backgroundColor: "#E2EBFF",
  },
  pillsContainer1: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: 40,
    borderRadius: 5,
    // backgroundColor: "#E2EBFF"
  },
  dashboard: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginTop: Platform.OS === "android" ? 20 : 30,
    marginBottom: Platform.OS === "android" ? 20 : 30,
    marginRight: 30,
    marginLeft: Platform.OS === "android" ? 50 : 30,
  },
  previewDashboard: {
    display: "flex",
    margin: Platform.OS === "ios" ? 30 : 20,
  },
  dashboardImage: {
    width: Platform.OS === "ios" ? 350 : 325,
    height: 190,
    borderRadius: 20,
    marginRight: Platform.OS === "android" ? 20 : 10,
  },
  headerContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: 10,
  },
  bottomContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 20,
    marginRight: 20,
  },
  margin: {
    margin: 10,
  },
  cardHeader: {
    color: "#FFFFFF",
    fontSize: 24,
    // fontWeight: 'bold',
    textAlign: "center",
    //fontFamily,
  },
  innerCardHeader: {
    fontSize: 16,
  },
  cardNumber: {
    color: "#FFFFFF",
    fontSize: 18,
    // fontWeight: 'bold',
    textAlign: "center",
    marginTop: 10,
    //fontFamily,
  },
  virtual: {
    color: "#FFFFFF",
    fontSize: 12,
    marginRight: 10,
    //fontFamily,
  },
  expiryDate: {
    color: "#FFFFFF",
    fontSize: 14,
    // marginRight: 10,
    //fontFamily,
  },
  card: {
    width: 24,
    height: 4,
    marginTop: 10,
  },
  cardDetailsText: {
    color: "#333333",
    fontSize: 16,
    //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  pillsText: {
    color: "#000000",
    fontSize: 16,
    textAlign: "center",
    //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  pillsText1: {
    color: "#333333",
    fontSize: 16,
    textAlign: "center",
    // //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  cardDetails: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: Platform.OS === "android" ? 5 : 10,
  },
  physicalCard: {
    color: "#333333",
    fontSize: 17,
    // //fontWeight: "bold",
    //fontFamily,
    marginTop: 30,
    marginBottom: 30,
  },
  transaction: {
    color: "#333333",
    fontSize: 18,
    //fontWeight: "bold",
    // textAlign: 'center',
    marginTop: 10,
    //fontFamily,
  },
  date: {
    color: "#686868",
    fontSize: 12,
    //fontWeight: "bold",
    // fontWeight: 'bold',
    // textAlign: 'center',
    marginTop: 20,
    marginBottom: 30,
    marginLeft: 10,
    //fontFamily,
  },
  description: {
    color: "#333333",
    fontSize: 14,
    //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  price: {
    color: "#E63946",
    fontSize: 14,
    //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  removeCard: {
    color: "#E63946",
    fontSize: 16,
    //fontWeight: "bold",
    // marginRight: 10,
    //fontFamily,
  },
  verticalSepperatorLine: {
    height: 1,
    backgroundColor: "rgba(50,52,54,0.2)",
    marginTop: 10,
    marginBottom: 10,
  },
  tranxContainer: {
    borderRadius: 5,
    borderWidth: 0.3,
    borderColor: "#022141",
    width: Platform.OS === "android" ? 340 : 370,
    marginTop: 20,
  },
  icon: {
    borderRadius: 50,
    backgroundColor: "#EAEAEA80",
    borderWidth: 1,
    borderColor: "#EAEAEA80",
  },
  requestCard: {
    position: "absolute",
    width: 200,
    height: 60,
    left: Platform.OS === "ios" ? 100 : 90,
    top: Platform.OS === "ios" ? 723 : 620,
    borderRadius: 10,
    // backgroundColor: "#E2EBFF",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  requestCardText: {
    color: "#000000",
    fontSize: 16,
    //fontWeight: "bold",
    textAlign: "center",
  },
  cardFeeContainer: {
    marginTop: 10,
    marginLeft: 30,
    marginRight: 30,
  },
  cardFeatureContainer: {
    marginTop: 20,
    marginLeft: 30,
    marginRight: 30,
    marginBottom: 20,
  },
  cardPreview: {
    color: "#022141",
    fontSize: 16,
    //fontWeight: "bold",
    marginTop: 20,
    marginBottom: 20,
  },
  cardFeeText: {
    color: "#022141",
    fontSize: 30,
    //fontWeight: "bold",
    textAlign: "center",
    marginTop: 10,
    // marginBottom: 20,
  },
  cardFee: {
    width: Platform.OS === "ios" ? 350 : "100%",
    height: 60,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D9D9D9",
  },
  button: {
    backgroundColor: "#000000",
    margin: 10,
    height: 48,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 50,
    position: "absolute",
    bottom: 10,
    left: 10,
    right: 10,
  },
  buttonText: {
    color: "white",
    //fontWeight: "bold",
    //fontFamily,
  },
  text1: {
    color: "#022141",
    fontSize: 18,
    //fontWeight: "bold",
    //fontFamily,
  },
  deliveryOptions: {
    width: Platform.OS === "ios" ? 350 : "100%",
    height: Platform.OS === "ios" ? 130 : 110,
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: "#0000FF",
    marginBottom: 20,
    padding: 10,
  },
  billingAddress: {
    width: Platform.OS === "ios" ? 350 : "100%",
    height: Platform.OS === "ios" ? 130 : 110,
    borderRadius: 10,
    borderWidth: 0.5,
    padding: 10,
  },
  spaceBetween: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  confirmText: {
    color: "#252525",
    fontSize: 14,
    paddingTop: 10,
  },
  confirmText1: {
    color: "grey",
    fontSize: 16,
    marginTop: 10,
  },
  confirmText2: {
    color: "grey",
    fontSize: 16,
    paddingTop: 10,
  },
  successContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    margin: Platform.OS === "ios" ? 20 : 40,
  },
  successText1: {
    color: "#252525",
    fontSize: 18,
    //fontWeight: "bold",
    textAlign: "center",
    //fontFamily,
  },
  successText2: {
    color: "#252525",
    fontSize: 18,
    //fontWeight: "bold",
    textAlign: "center",
    marginTop: 40,
    //fontFamily,
  },
});

export default styles;
